# !/usr/bin/python
# -*- coding:utf-8 -*-


# 系统上传文件类别
CATEGORY_UPLOAD_FILE_IMG_TXT = 4  # 富文本图片
CATEGORY_CERTIFICATE_UE = 9  # UEditor
CATEGORY_UPLOAD_FILE_OTHER = 99  # 其他图片
CATEGORY_UPLOAD_FILE_LIST = [
    CATEGORY_UPLOAD_FILE_IMG_TXT,
    CATEGORY_UPLOAD_FILE_OTHER
]
CATEGORY_UPLOAD_FILE_DICT = {
    CATEGORY_UPLOAD_FILE_IMG_TXT: '富文本图片',
    CATEGORY_UPLOAD_FILE_OTHER: '其他'
}

# 用户状态
STATUS_USER_ACTIVE = 1
STATUS_USER_INACTIVE = 2
STATUS_USER_LIST = [STATUS_USER_ACTIVE, STATUS_USER_INACTIVE]
STATUS_USER_DICT = {
    STATUS_USER_ACTIVE: '活动的',
    STATUS_USER_INACTIVE: '锁定的'
}

# 性别
SEX_NONE = 0
SEX_MALE = 1
SEX_FEMALE = 2
SEX_LIST = [SEX_NONE, SEX_MALE, SEX_FEMALE]
SEX_DICT = {
    SEX_NONE: '无',
    SEX_MALE: '男',
    SEX_FEMALE: '女'
}

# 角色状态
STATUS_ROLE_ACTIVE = 1
STATUS_ROLE_INACTIVE = 2
STATUS_ROLE_LIST = [STATUS_ROLE_ACTIVE, STATUS_ROLE_INACTIVE]
STATUS_ROLE_DICT = {
    STATUS_ROLE_ACTIVE: '活动的',
    STATUS_ROLE_INACTIVE: '锁定的'
}

STATUS_INACTIVE = 0  # 禁用状态
STATUS_ACTIVE = 1  # 启用状态
STATUS_LIST = [STATUS_ACTIVE, STATUS_INACTIVE]
STATUS_DICT = {
    STATUS_ACTIVE: '启用',
    STATUS_INACTIVE: '禁用'
}

# APP用户状态
STATUS_APP_USER_INVALID = 0
STATUS_APP_USER_EFFECTIVE = 1
STATUS_APP_USER_LIST = [STATUS_APP_USER_INVALID, STATUS_APP_USER_EFFECTIVE]
STATUS_APP_USER_DICT = {
    STATUS_APP_USER_INVALID: '无效',
    STATUS_APP_USER_EFFECTIVE: '有效'
}

# 是否为会员
STATUS_USER_NOT_MEMBER = 0
STATUS_USER_IS_MEMBER = 1
STATUS_USER_MEMBER_LIST = [STATUS_USER_NOT_MEMBER, STATUS_USER_IS_MEMBER]
STATUS_USER_MEMBER_DICT = {
    STATUS_USER_NOT_MEMBER: '非会员',
    STATUS_USER_IS_MEMBER: '会员'
}

# 用户照片及视频备份状态
STATUS_USER_AUTO_BACKUP_INACTIVE = 0
STATUS_USER_AUTO_BACKUP_ACTIVE = 1
STATUS_USER_AUTO_BACKUP_LIST = [STATUS_USER_AUTO_BACKUP_INACTIVE, STATUS_USER_AUTO_BACKUP_ACTIVE]
STATUS_USER_AUTO_BACKUP_DICT = {
    STATUS_USER_AUTO_BACKUP_INACTIVE: '自动备份关闭',
    STATUS_USER_AUTO_BACKUP_ACTIVE: '自动备份开启'
}

# 会员类型
STATUS_GENERAL_MEMBER = 1
STATUS_SUPER_MEMBER = 2
STATUS_MEMBER_TYPE_LIST = [STATUS_GENERAL_MEMBER, STATUS_SUPER_MEMBER]
STATUS_MEMBER_TYPE_DICT = {
    STATUS_GENERAL_MEMBER: '普通会员',
    STATUS_SUPER_MEMBER: '超级会员'
}

# 会员状态
STATUS_MEMBER_INVALID = 0
STATUS_MEMBER_EFFECTIVE = 1
STATUS_MEMBER_LIST = [STATUS_MEMBER_INVALID, STATUS_MEMBER_EFFECTIVE]
STATUS_MEMBER_DICT = {
    STATUS_MEMBER_INVALID: '无效',
    STATUS_MEMBER_EFFECTIVE: '有效'
}

# 会员自动续费状态
STATUS_MEMBER_NOT_AUTO_RENEW = 0
STATUS_MEMBER_IS_AUTO_RENEW = 1
STATUS_MEMBER_AUTO_RENEW_LIST = [STATUS_MEMBER_NOT_AUTO_RENEW, STATUS_MEMBER_IS_AUTO_RENEW]
STATUS_MEMBER_AUTO_RENEW_DICT = {
    STATUS_MEMBER_NOT_AUTO_RENEW: '未开通自动续费',
    STATUS_MEMBER_IS_AUTO_RENEW: '已开通自动续费'
}

# 相册表类型状态
STATUS_ALBUM_TYPE_PIC = 1
STATUS_ALBUM_TYPE_VIDEO = 2
STATUS_ALBUM_TYPE_LIST = [STATUS_ALBUM_TYPE_PIC, STATUS_ALBUM_TYPE_VIDEO]
STATUS_ALBUM_TYPE_DICT = {
    STATUS_ALBUM_TYPE_PIC: '图片',
    STATUS_ALBUM_TYPE_VIDEO: '视频'
}

# 相册表分享状态
STATUS_ALBUM_ATTR_SELF = 1
STATUS_ALBUM_TYPE_SHARE = 2
STATUS_ALBUM_ATTR_LIST = [STATUS_ALBUM_ATTR_SELF, STATUS_ALBUM_TYPE_SHARE]
STATUS_ALBUM_ATTR_DICT = {
    STATUS_ALBUM_ATTR_SELF: '自建',
    STATUS_ALBUM_TYPE_SHARE: '分享'
}

# 相册表状态
STATUS_ALBUM_INVALID = 0
STATUS_ALBUM_EFFECTIVE = 1
STATUS_ALBUM_LIST = [STATUS_ALBUM_INVALID, STATUS_ALBUM_EFFECTIVE]
STATUS_ALBUM_DICT = {
    STATUS_ALBUM_INVALID: '无效',
    STATUS_ALBUM_EFFECTIVE: '有效'
}

# 文件对象状态
STATUS_FILE_INVALID = 0
STATUS_FILE_EFFECFIVE = 1
STATUS_FILE_LIST = [STATUS_FILE_INVALID, STATUS_FILE_EFFECFIVE]
STATUS_FILE_DICT = {
    STATUS_FILE_INVALID: '无效',
    STATUS_FILE_EFFECFIVE: '有效',
}

# 文件上传类型状态
STATUS_FILE_UPLOAD_TYPE_PIC = 1
STATUS_FILE_UPLOAD_TYPE_VIDEO = 2
STATUS_FILE_UPLOAD_TYPE_LIST = [STATUS_FILE_UPLOAD_TYPE_PIC, STATUS_FILE_UPLOAD_TYPE_VIDEO]
STATUS_FILE_UPLOAD_TYPE_DICT = {
    STATUS_FILE_UPLOAD_TYPE_PIC: '图片',
    STATUS_FILE_UPLOAD_TYPE_VIDEO: '视频'
}

# 文件上传下载状态
STATUS_FILE_TRANSFER_UPLOAD = 1
STATUS_FILE_TRANSFER_DOWNLOAD = 2
STATUS_FILE_TRANSFER_LIST = [STATUS_FILE_TRANSFER_UPLOAD, STATUS_FILE_TRANSFER_DOWNLOAD]
STATUS_FILE_TRANSFER_DICT = {
    STATUS_FILE_TRANSFER_UPLOAD: '上传',
    STATUS_FILE_TRANSFER_DOWNLOAD: '下载'
}

# 文件传输状态
STATUS_TASK_TRANSFER_DOING = 1
STATUS_TASK_TRANSFER_PAUSE = 2
STATUS_TASK_TRANSFER_DONE = 3
STATUS_TASK_TRANSFER_LIST = [STATUS_TASK_TRANSFER_DOING, STATUS_TASK_TRANSFER_PAUSE, STATUS_TASK_TRANSFER_DONE]
STATUS_TASK_TRANSFER_DICT = {
    STATUS_TASK_TRANSFER_DOING: '进行中',
    STATUS_TASK_TRANSFER_PAUSE: '已暂停',
    STATUS_TASK_TRANSFER_DONE: '已完成'
}

# 文件传输显示状态
STATUS_TASK_NOT_SHOW = 0
STATUS_TASK_IS_SHOW = 1
STATUS_TASK_SHOW_LIST = [STATUS_TASK_NOT_SHOW, STATUS_TASK_IS_SHOW]
STATUS_TASK_SHOW_DICT = {
    STATUS_TASK_NOT_SHOW: '隐藏',
    STATUS_TASK_IS_SHOW: '显示'
}

# 帮助反馈类别状态
STATUS_FEEDBACK_CATEGORY_PERSONAL = 1
STATUS_FEEDBACK_CATEGORY_PUBLIC = 2
STATUS_FEEDBACK_CATEGORY_LIST = [STATUS_FEEDBACK_CATEGORY_PERSONAL, STATUS_FEEDBACK_CATEGORY_PUBLIC]
STATUS_FEEDBACK_CATEGORY_DICT = {
    STATUS_FEEDBACK_CATEGORY_PERSONAL: '个人',
    STATUS_FEEDBACK_CATEGORY_PUBLIC: '公共'
}

# 帮助反馈状态
STATUS_FEEDBACK_INVALID = 0
STATUS_FEEDBACK_EFFECTIVE = 1
STATUS_FEEDBACK_LIST = [STATUS_FEEDBACK_INVALID, STATUS_FEEDBACK_EFFECTIVE]
STATUS_FEEDBACK_DICT = {
    STATUS_FEEDBACK_INVALID: '无效',
    STATUS_FEEDBACK_EFFECTIVE: '有效'
}

# APP 更新状态
STATUS_NOT_FORCE_UPDATE = 0
STATUS_IS_FORCE_UPDATE = 1
STATUS_FORCR_UPDATE_LIST = [STATUS_NOT_FORCE_UPDATE, STATUS_IS_FORCE_UPDATE]
STATUS_FORCR_UPDATE_DICT = {
    STATUS_NOT_FORCE_UPDATE: '不强制更新',
    STATUS_IS_FORCE_UPDATE: '强制更新'
}

# APP 版本状态
STATUS_PREV_VERSION = 0
STATUS_LATEST_VERSION = 1
STATUS_VERSION_LIST = [STATUS_PREV_VERSION, STATUS_LATEST_VERSION]
STATUS_VERSION_DICT = {
    STATUS_PREV_VERSION: '上一版',
    STATUS_LATEST_VERSION: '最新版'
}

# APP 发布状态
STATUS_UNPUBLISHED_VERSION = 0
STATUS_PUBLISHED_VERSION = 1
STATUS_PUBLISH_VERSION_LIST = [STATUS_UNPUBLISHED_VERSION, STATUS_PUBLISHED_VERSION]
STATUS_PUBLISH_VERSION_DICT = {
    STATUS_UNPUBLISHED_VERSION: '未发布',
    STATUS_PUBLISHED_VERSION: '已发布'
}